#!/bin/bash

echo "Script requires the server IP as first argument, and server ssh key path as second, and port for incoming ssh connections to the Pi as third"

host_name=$1
user_name=$2
rsa_key_path=$3

echo "Geting IP from server"

PiIP=`ssh $2@$1 -i $3 'tail -n 1 PiIP'`
echo "PiIP is: $PiIP"
ssh pi@$PiIP -p $3
