#!/bin/bash

echo "Script requires the server username as first argument, server ip as second, server rsa key as third"
echo "Pi rsa key as fourth, and port number for incoming ssh connections to the Pi as fifth"

cloudserver_username=$1
cloudserver_ip=$2
cloud_rsakey_path=$3
pi_rsakey_path=$4
pi_wan_port=$5

#get the ip
PiIP=`ssh $cloudserver_username@$cloudserver_ip -i $cloud_rsakey_path 'tail -n 1 PiIP'`

sshfs pi@$PiIP:/home/pi/ ~/Pi -p $pi_wan_port -o IdentityFile=$pi_rsakey_path
